export const PAGINATION_ENUM = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
}

export const ADMIN_VIEWS = {
  TABLE: 'TABLE',
  CSV_IMPORTER: 'CSV_IMPORTER',
  ANIMATION_SETTINGS: 'ANIMATION_SETTINGS',
}
